# Generated by Django 4.0.3 on 2022-03-26 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('Item_Name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Ponderation', models.IntegerField(verbose_name='Grades percentage, from 0 to 100%')),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_Nif', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Surname', models.CharField(max_length=50)),
                ('Expedient', models.FloatField(blank=True, default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('Subject_Name', models.CharField(choices=[('IR', 'Ingenirería de Requisitos'), ('MP', 'Modelos de Proceso'), ('QMI', 'Gestión y mejora de la calidad'), ('WP', 'Proyecto Web'), ('ABDIS', 'Ampliación de bases de datos e Ingeniería del Software')], max_length=5, primary_key=True, serialize=False)),
                ('Course', models.CharField(choices=[('3', 'Tercer curso')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Schedule', models.CharField(choices=[('9', '9:00 - 10:50'), ('11', '11:10 - 13:00'), ('15', '15:00 - 16.50'), ('17', '17:10 - 19:00'), ('19', '19:10 - 21:00')], max_length=2)),
                ('Classroom', models.CharField(choices=[('3', '0.03'), ('4', '0.04'), ('1.01', 'Alcatel'), ('1.03', 'Sala master')], max_length=4)),
                ('Professor', models.CharField(max_length=50)),
                ('Day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3)),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGrades.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Punctuation', models.FloatField(default=0, max_length=5)),
                ('Item_Submitted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGrades.item')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGrades.student')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='Item_From_Subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGrades.subject'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mean', models.FloatField(default=0, editable=False)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGrades.student')),
                ('Subject_Grades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGrades.subject')),
            ],
            options={
                'unique_together': {('Student', 'Subject_Grades')},
            },
        ),
    ]
