# Generated by Django 4.0.3 on 2022-03-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGrades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Ranking',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='Ponderation',
            field=models.FloatField(verbose_name='Grades percentage, from 0 to 100%'),
        ),
    ]
