# Generated by Django 4.0.3 on 2022-03-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGrades', '0002_student_ranking_alter_item_ponderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Course',
            field=models.IntegerField(default='3', max_length=1),
            preserve_default=False,
        ),
    ]
