# Generated by Django 4.0.3 on 2022-03-27 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGrades', '0003_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Best_Student',
            field=models.ForeignKey(default='11111111A', editable=False, on_delete=django.db.models.deletion.CASCADE, to='SGrades.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='Course',
            field=models.IntegerField(),
        ),
    ]
